#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH
mkdir -p ${OPENSHIFT_ORS_DIR}log
mkdir -p ${OPENSHIFT_ORS_DIR}run

nohup ${OPENSHIFT_REPO_DIR}diy/testrubyserver.rb $OPENSHIFT_ORS_IP ${OPENSHIFT_REPO_DIR}diy > ${OPENSHIFT_ORS_DIR}log/server.log 2>&1 &
