#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_ORS_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_ORS_DIR/log/server.log 2>&1 &
