#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH
ME="$(cd `dirname $BASH_SOURCE` && pwd)"
source $ME/_utils

if output=$(curl http://$OPENSHIFT_ORS_IP:$OPENSHIFT_ORS_PORT 2>&1); then
  client_result "Application is running"
else
  client_result "Application is either stopped or inaccessible"
fi

if isrunning; then
  client_result "ORS is running"
else
  client_result "ORS is stopped"
fi
