#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH
ME="$(cd `dirname $BASH_SOURCE` && pwd)"
source $ME/_utils

if [ -z "$(ps -ef | grep testrubyserver.rb | grep -v grep)" ]; then
  client_result "Application is already stopped"
else
  kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi

if isrunning; then
  if [ -f "$PIDFILE" ]; then
    pid=$(cat $PIDFILE);
    killtree $pid
  else
    client_result "Failed to locate ORS PID File" 1>&2
  fi
else
  client_result "ORS is already stopped"
fi

rm -f $PIDFILE
